version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    init: true
    volumes:
      # Use a named volume for the source code
      - my-app:/workspace
      # Persist VS Code extensions between rebuilds
      - vscode-extensions:/root/.vscode-server/extensions
      # And/or for VS Code Insiders
      - vscode-extensions-insiders:/root/.vscode-server-insiders/extensions

    container_name: bullmq-workshop
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  ingress:
    image: node:18-alpine
    volumes:
      - ../:/workspace
    command:
      node --watch /workspace/serve-http.js
    ports:
      - "80:80"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - PORT=80
      - ADDRESS=0.0.0.0
      - URL_PREFIX=/redis
    expose:
      - 80

  bull-board:
    image: node:18-alpine
    volumes:
      - ../:/workspace

    command: node --watch /workspace/serve-bull-board.js

    expose:
      - 80

volumes:
  my-app:
  vscode-extensions:
  vscode-extensions-insiders:
  redis-data:
