version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    init: true
    volumes:
      # Use a named volume for the source code
      - my-app:/workspace
      # Persist VS Code extensions between rebuilds
      - vscode-extensions:/root/.vscode-server/extensions
      # And/or for VS Code Insiders
      - vscode-extensions-insiders:/root/.vscode-server-insiders/extensions

    container_name: bullmq-workshop
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  ingress:
    image: node:18-alpine
    volumes:
      - ../:/workspace
    command: |
      node --watch /workspace/serve-http.js

    ports:
      - "4444:80"

  redis:
    image: redis:7-alpine
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
    expose:
      - 6379

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # The postgress container will execute these files when initializing
      # This only happens if postgres determines no database has previously been
      # Initialized, so this script can assume it is running on a clean instance
      - ../init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    ports:
      - "6543:5432"
    stop_grace_period: 1s

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - PORT=80
      - ADDRESS=0.0.0.0
      - URL_PREFIX=/redis
    expose:
      - 80
    labels:
      org.example.proxyPath: /redis

  graphql:
    image: node:18-alpine
    volumes:
      - ../:/workspace

    command: npx ts-node-dev --transpile-only --respawn /workspace/serve-graphql.ts

    expose:
      - 80

    labels:
      org.example.proxyPath: /graphql

    environment:
      - BASE_PATH=/graphql

    depends_on:
      - redis
      - postgres

  bull-board:
    image: node:18-alpine
    volumes:
      - ../:/workspace

    environment:
      - BASE_PATH=/bullmq

    command: node --watch /workspace/serve-bull-board.js

    expose:
      - 80

    labels:
      org.example.proxyPath: /bullmq

  workers:
    image: node:18-alpine
    volumes:
      - ../:/workspace

    command: node --watch /workspace/workers.js

  # shell:
  # image: node:18-alpine
  # volumes:
  #   - ../:/workspace

  # command: node -r /workspace/queues.js

volumes:
  my-app:
  vscode-extensions:
  vscode-extensions-insiders:
  redis-data:
  postgres-data:
